"""Desktop viewer for GeoTIFF proefsleuven with KLIC overlays."""

from .settings_ui import install_settings_ui_patch
from .settings_general_layout_patch import install_settings_general_layout_patch
from .settings_kickthemap_autosave_patch import (
    install_settings_kickthemap_autosave_patch,
)
from .dynamic_visibility_finalize_patch import install_dynamic_visibility_finalize_patch
from .template_dynamic_profile_leader_patch import install_dynamic_profile_leader_patch
from .profile_leader_original_definition_patch import install_profile_leader_original_definition_patch
from .literal_profile_leader_donor_patch import install_literal_profile_leader_donor_patch
from .profile_leader_circle_style_patch import install_profile_leader_circle_style_patch
from .top_level_profile_leader_patch import install_top_level_profile_leader_patch


install_settings_ui_patch()
install_settings_general_layout_patch()
install_settings_kickthemap_autosave_patch()
install_dynamic_visibility_finalize_patch()
install_dynamic_profile_leader_patch()
install_profile_leader_original_definition_patch()
install_literal_profile_leader_donor_patch()
install_profile_leader_circle_style_patch()
install_top_level_profile_leader_patch()