"""Desktop viewer for GeoTIFF proefsleuven with KLIC overlays."""

from .settings_ui import install_settings_ui_patch
from .settings_general_layout_patch import install_settings_general_layout_patch
from .settings_kickthemap_autosave_patch import (
    install_settings_kickthemap_autosave_patch,
)
from .dynamic_visibility_finalize_patch import install_dynamic_visibility_finalize_patch
from .marxact_direction_patch import install_marxact_direction_patch
from .marxact_midpoint_snap_patch import install_marxact_midpoint_snap_patch
from .template_bgt_fetch_patch import install_template_bgt_fetch_patch
from .template_asset_memory_patch import install_template_asset_memory_patch
from .template_export_performance_patch import install_template_export_performance_patch
from .virtual_trench_template_patch import install_virtual_trench_template_patch
from .pdok_high_quality_patch import install_pdok_high_quality_patch
from .marxact_boundary_patch import install_marxact_boundary_patch
from .marxact_local_cross_section_patch import install_marxact_local_cross_section_patch
from .marxact_live_render_patch import install_marxact_live_render_patch
from .marxact_alignment_ui_patch import install_marxact_alignment_ui_hook
from .dxf_template_pipeline_patch import install_dxf_template_pipeline_patch
from .dxf_template_pipeline_bridge import install_dxf_template_pipeline_bridge
from .dxf_template_pipeline_v3_patch import install_dxf_template_pipeline_v3_patch
from .dxf_template_pipeline_v4_patch import install_dxf_template_pipeline_v4_patch
from .dxf_template_pipeline_v5_patch import install_dxf_template_pipeline_v5_patch
from .dxf_template_pipeline_v6_patch import install_dxf_template_pipeline_v6_patch
from .dxf_template_pipeline_v7_patch import install_dxf_template_pipeline_v7_patch


install_settings_ui_patch()
install_settings_general_layout_patch()
install_settings_kickthemap_autosave_patch()
install_dynamic_visibility_finalize_patch()
install_marxact_direction_patch()
install_marxact_midpoint_snap_patch()
install_template_bgt_fetch_patch()
install_template_asset_memory_patch()
install_template_export_performance_patch()
install_virtual_trench_template_patch()
install_pdok_high_quality_patch()
install_marxact_boundary_patch()
install_marxact_local_cross_section_patch()
install_marxact_live_render_patch()
install_marxact_alignment_ui_hook()
install_dxf_template_pipeline_patch()
install_dxf_template_pipeline_bridge()
install_dxf_template_pipeline_v3_patch()
install_dxf_template_pipeline_v4_patch()
install_dxf_template_pipeline_v5_patch()
install_dxf_template_pipeline_v6_patch()
install_dxf_template_pipeline_v7_patch()
