from __future__ import annotations

import os
from pathlib import Path
import shutil
from typing import Any

from . import dxf_template_pipeline_patch as pipeline
from . import dxf_template_pipeline_v3_patch as pipeline_v3
from . import dxf_template_pipeline_v4_patch as pipeline_v4
from . import dxf_template_pipeline_v7_patch as pipeline_v7
from . import template_reverse_patch as reverse_patch


PATCH_VERSION = 2


def _same_path(left: object, right: object) -> bool:
    try:
        left_path = Path(left).expanduser().resolve(strict=False)
        right_path = Path(right).expanduser().resolve(strict=False)
    except (OSError, TypeError, ValueError):
        return False
    return os.path.normcase(str(left_path)) == os.path.normcase(str(right_path))


def _materialize_reverse_asset(
    exporter: Any,
    source_path: Path,
    asset_dir: Path,
    preferred_name: str,
    *,
    counter_name: str,
) -> Path:
    """Ensure a reused reverse raster physically exists in the reverse asset dir.

    V4 may intentionally reuse a raster generated during the normal pass. Returning
    that normal-pass path is sufficient for direct image insertion, but the reverse
    merge pipeline treats ``.<name>.sleufbase-reverse-source_assets`` as a temporary
    self-contained bundle and later relocates its image files. A reused path outside
    that directory therefore leaves the reverse IMAGEDEF pointing at an asset that
    was never materialized in the bundle.

    Hard-link where possible (cheap on the normal Windows/NTFS path) and fall back
    to copying. The normal source asset is never moved or deleted here.
    """

    source = Path(source_path).expanduser().resolve(strict=False)
    target_root = Path(asset_dir).expanduser().resolve(strict=False)
    if not source.exists():
        raise FileNotFoundError(f"Reverse rasterbron ontbreekt: {source}")

    # Assets generated by the regular reverse renderer are already self-contained.
    if _same_path(source.parent, target_root):
        return source

    target_root.mkdir(parents=True, exist_ok=True)
    destination = Path(exporter._unique_raster_copy_path(target_root, preferred_name))
    destination.parent.mkdir(parents=True, exist_ok=True)

    if _same_path(source, destination):
        return source

    try:
        os.link(source, destination)
        pipeline._increment_pair_counter(f"{counter_name}_linked")
    except OSError:
        shutil.copy2(source, destination)
        pipeline._increment_pair_counter(f"{counter_name}_copied")
    return destination.resolve(strict=False)


def _transfer_reverse_image_assets_v8(
    reverse_document,
    reverse_source_path: Path,
    final_output_path: Path,
) -> Path:
    """Relocate reverse rasters once even when several IMAGEDEFs share a file.

    V3 moves files that live in the temporary reverse asset directory. Its old
    implementation checked ``source.exists()`` before consulting the per-source
    transfer cache. If two different IMAGEDEF handles referenced the same PNG, the
    first IMAGEDEF moved the file and the second one immediately failed with
    ``Reverse rasterbestand ontbreekt``. Check the cache first so all definitions
    can safely reuse the already-relocated destination.
    """

    target_dir = final_output_path.parent / f"{final_output_path.stem}_reverse_assets"
    target_dir.mkdir(parents=True, exist_ok=True)
    temporary_root = reverse_patch._source_asset_dir(reverse_source_path).resolve(strict=False)
    processed_defs: set[str] = set()
    transferred_by_source: dict[str, Path] = {}

    for block in reverse_document.blocks:
        block_name = str(getattr(block, "name", "") or "").upper()
        if not block_name.startswith(reverse_patch.VARIANT_LAYER_PREFIX) or not block_name.endswith(
            f"_{reverse_patch.REVERSE_MODE}{reverse_patch.VARIANT_BLOCK_SUFFIX}"
        ):
            continue
        for image in block.query("IMAGE"):
            try:
                image_def = image.image_def
            except Exception:
                image_def = None
            if image_def is None:
                continue
            handle = str(getattr(image_def.dxf, "handle", "") or id(image_def))
            if handle in processed_defs:
                continue
            processed_defs.add(handle)

            filename = str(getattr(image_def.dxf, "filename", "") or "").strip()
            if not filename:
                continue
            source = Path(filename)
            if not source.is_absolute():
                source = reverse_source_path.parent / source
            source = source.resolve(strict=False)
            source_key = os.path.normcase(str(source))

            # Important: consult the cache before checking the source path. Assets
            # inside the temporary reverse bundle are moved on their first use, so
            # their original path is expected to disappear afterwards.
            destination = transferred_by_source.get(source_key)
            if destination is None:
                if not source.exists():
                    raise FileNotFoundError(f"Reverse rasterbestand ontbreekt: {source}")
                destination = target_dir / source.name
                mode = pipeline_v3._relocate_reverse_asset(
                    source,
                    destination,
                    temporary_root,
                )
                destination = destination.resolve(strict=False)
                transferred_by_source[source_key] = destination
                pipeline_v3._increment(f"reverse_assets_{mode}")
            else:
                pipeline_v3._increment("reverse_assets_duplicate_source_reused")
                if not destination.exists():
                    raise FileNotFoundError(
                        f"Verplaatst reverse rasterbestand ontbreekt: {destination}"
                    )

            image_def.dxf.filename = str(destination)
    return target_dir


def install_dxf_template_pipeline_v8_patch() -> None:
    """Make the normal/reverse raster pipeline self-contained and dedupe-safe.

    Two failure modes are handled here:
    * reused normal TIFF/map rasters are materialized inside the temporary reverse
      asset bundle before the reverse document is merged;
    * multiple reverse IMAGEDEFs that reference the same temporary PNG reuse the
      first relocated destination instead of treating the moved source as missing.
    """

    from .cadastral_export import CadastralDxfExporter

    pipeline_v7.install_dxf_template_pipeline_v7_patch()
    if int(
        getattr(CadastralDxfExporter, "_sleufbase_dxf_template_pipeline_v8_version", 0)
        or 0
    ) >= PATCH_VERSION:
        return

    previous_tiff = CadastralDxfExporter._build_template_tiff_raster
    previous_map = CadastralDxfExporter._build_template_map_raster

    def _build_template_tiff_raster_v8(
        self,
        asset_dir,
        layer,
        label,
        index,
        road_orientation_paths,
        terrain_boundary_paths,
        profile=None,
        reverse_orientation=False,
    ):
        result = previous_tiff(
            self,
            asset_dir,
            layer,
            label,
            index,
            road_orientation_paths,
            terrain_boundary_paths,
            profile=profile,
            reverse_orientation=reverse_orientation,
        )
        if pipeline_v4._mode(self) != reverse_patch.REVERSE_MODE:
            return result
        return _materialize_reverse_asset(
            self,
            Path(result),
            Path(asset_dir),
            f"{label}_geotiff.png",
            counter_name="reverse_tiff_materialized",
        )

    def _build_template_map_raster_v8(
        self,
        asset_dir,
        layer,
        label,
        index,
        trench_mode,
        centerline_color,
        label_color,
        page_exporter,
        dxf_overlays,
        map_comments,
        background_provider,
        background_attribution,
        reference_annotation=None,
    ):
        result = previous_map(
            self,
            asset_dir,
            layer,
            label,
            index,
            trench_mode,
            centerline_color,
            label_color,
            page_exporter,
            dxf_overlays,
            map_comments,
            background_provider,
            background_attribution,
            reference_annotation=reference_annotation,
        )
        if pipeline_v4._mode(self) != reverse_patch.REVERSE_MODE:
            return result
        return _materialize_reverse_asset(
            self,
            Path(result),
            Path(asset_dir),
            f"{label}_kaart.png",
            counter_name="reverse_map_materialized",
        )

    # V7 resolves this module global at merge time, so replacing it here also
    # protects the in-memory normal/reverse merge path without an extra DXF pass.
    pipeline_v3._transfer_reverse_image_assets = _transfer_reverse_image_assets_v8
    CadastralDxfExporter._build_template_tiff_raster = _build_template_tiff_raster_v8
    CadastralDxfExporter._build_template_map_raster = _build_template_map_raster_v8
    CadastralDxfExporter._sleufbase_dxf_template_pipeline_v8_version = PATCH_VERSION
    CadastralDxfExporter.SLEUFBASE_REVERSE_ASSET_MATERIALIZATION = True
    CadastralDxfExporter.SLEUFBASE_REVERSE_RASTER_SELF_CONTAINED = True
    CadastralDxfExporter.SLEUFBASE_REVERSE_DUPLICATE_IMAGEDEF_SAFE = True
