from __future__ import annotations

import os
from pathlib import Path
import shutil
from typing import Any

from . import dxf_template_pipeline_patch as pipeline
from . import dxf_template_pipeline_v4_patch as pipeline_v4
from . import dxf_template_pipeline_v7_patch as pipeline_v7
from . import template_reverse_patch as reverse_patch


PATCH_VERSION = 1


def _same_path(left: object, right: object) -> bool:
    try:
        left_path = Path(left).expanduser().resolve(strict=False)
        right_path = Path(right).expanduser().resolve(strict=False)
    except (OSError, TypeError, ValueError):
        return False
    return os.path.normcase(str(left_path)) == os.path.normcase(str(right_path))


def _materialize_reverse_asset(
    exporter: Any,
    source_path: Path,
    asset_dir: Path,
    preferred_name: str,
    *,
    counter_name: str,
) -> Path:
    """Ensure a reused reverse raster physically exists in the reverse asset dir.

    V4 may intentionally reuse a raster generated during the normal pass. Returning
    that normal-pass path is sufficient for direct image insertion, but the reverse
    merge pipeline treats ``.<name>.sleufbase-reverse-source_assets`` as a temporary
    self-contained bundle and later relocates its image files. A reused path outside
    that directory therefore leaves the reverse IMAGEDEF pointing at an asset that
    was never materialized in the bundle.

    Hard-link where possible (cheap on the normal Windows/NTFS path) and fall back
    to copying. The normal source asset is never moved or deleted here.
    """

    source = Path(source_path).expanduser().resolve(strict=False)
    target_root = Path(asset_dir).expanduser().resolve(strict=False)
    if not source.exists():
        raise FileNotFoundError(f"Reverse rasterbron ontbreekt: {source}")

    # Assets generated by the regular reverse renderer are already self-contained.
    if _same_path(source.parent, target_root):
        return source

    target_root.mkdir(parents=True, exist_ok=True)
    destination = Path(exporter._unique_raster_copy_path(target_root, preferred_name))
    destination.parent.mkdir(parents=True, exist_ok=True)

    if _same_path(source, destination):
        return source

    try:
        os.link(source, destination)
        pipeline._increment_pair_counter(f"{counter_name}_linked")
    except OSError:
        shutil.copy2(source, destination)
        pipeline._increment_pair_counter(f"{counter_name}_copied")
    return destination.resolve(strict=False)


def install_dxf_template_pipeline_v8_patch() -> None:
    """Keep every reverse TIFF/map raster inside the reverse temporary bundle.

    This fixes pair exports where V4 reuses a normal TIFF or pre-rendered map and
    consequently returns a path outside the reverse source asset directory. The
    reverse DXF merge expects those raster assets to be present in its own bundle;
    materializing them here makes that invariant explicit without giving up the
    expensive normal->reverse raster reuse.
    """

    from .cadastral_export import CadastralDxfExporter

    pipeline_v7.install_dxf_template_pipeline_v7_patch()
    if int(
        getattr(CadastralDxfExporter, "_sleufbase_dxf_template_pipeline_v8_version", 0)
        or 0
    ) >= PATCH_VERSION:
        return

    previous_tiff = CadastralDxfExporter._build_template_tiff_raster
    previous_map = CadastralDxfExporter._build_template_map_raster

    def _build_template_tiff_raster_v8(
        self,
        asset_dir,
        layer,
        label,
        index,
        road_orientation_paths,
        terrain_boundary_paths,
        profile=None,
        reverse_orientation=False,
    ):
        result = previous_tiff(
            self,
            asset_dir,
            layer,
            label,
            index,
            road_orientation_paths,
            terrain_boundary_paths,
            profile=profile,
            reverse_orientation=reverse_orientation,
        )
        if pipeline_v4._mode(self) != reverse_patch.REVERSE_MODE:
            return result
        return _materialize_reverse_asset(
            self,
            Path(result),
            Path(asset_dir),
            f"{label}_geotiff.png",
            counter_name="reverse_tiff_materialized",
        )

    def _build_template_map_raster_v8(
        self,
        asset_dir,
        layer,
        label,
        index,
        trench_mode,
        centerline_color,
        label_color,
        page_exporter,
        dxf_overlays,
        map_comments,
        background_provider,
        background_attribution,
        reference_annotation=None,
    ):
        result = previous_map(
            self,
            asset_dir,
            layer,
            label,
            index,
            trench_mode,
            centerline_color,
            label_color,
            page_exporter,
            dxf_overlays,
            map_comments,
            background_provider,
            background_attribution,
            reference_annotation=reference_annotation,
        )
        if pipeline_v4._mode(self) != reverse_patch.REVERSE_MODE:
            return result
        return _materialize_reverse_asset(
            self,
            Path(result),
            Path(asset_dir),
            f"{label}_kaart.png",
            counter_name="reverse_map_materialized",
        )

    CadastralDxfExporter._build_template_tiff_raster = _build_template_tiff_raster_v8
    CadastralDxfExporter._build_template_map_raster = _build_template_map_raster_v8
    CadastralDxfExporter._sleufbase_dxf_template_pipeline_v8_version = PATCH_VERSION
    CadastralDxfExporter.SLEUFBASE_REVERSE_ASSET_MATERIALIZATION = True
    CadastralDxfExporter.SLEUFBASE_REVERSE_RASTER_SELF_CONTAINED = True
